# 7. To Scrape the details of Data scientist recruiters from naukri.com.

In [1]:
# importing required libraries.
import pandas as pd
import selenium
import time

#importing Webdriver
from selenium import webdriver

#importing Exception Handling
from selenium.common.exceptions import NoSuchElementException
#importing keys
from selenium.webdriver.common.keys import Keys

In [2]:
#connecting the web driver.
driver=webdriver.Chrome(r'C:\Program Files (x86)\chromedriver_win32\chromedriver.exe')

In [3]:
#connecting the website.
driver.get('https://www.naukri.com/')
time.sleep(2)

In [4]:
#clicking the recruiters button
recruiter=driver.find_element_by_xpath("//*[@id='root']/div[1]/div/ul[1]/li[2]/a")
driver.get(recruiter.get_attribute('href'))
time.sleep(3)

In [5]:
#filling the search bar
searchbar=driver.find_element_by_xpath("//*[@id='skill']/div[1]/div[2]/input")

searchbar.send_keys("Data Scientist")
searchbar.send_keys(Keys.ENTER)

In [6]:
#creating empty list
Name=[]
Designation=[]
Company=[]
Skills=[]
Location=[]

In [7]:
#creating name list
name=driver.find_elements_by_xpath("//*[@id='tabP-1']/div/div[1]/div[1]/div[1]/p/a[1]/span")
for i in name:
    try:
        Name.append(i.text)
    except:
        Name.append("-")

In [8]:
#creating designation list
designation=driver.find_elements_by_xpath("//*[@id='tabP-1']/div/div[1]/div[1]/div[1]/p/span[1]")
for i in designation:
    try:
        Designation.append(i.text)
    except:
        Designation.append("-")

In [9]:
#creating the company list
company=driver.find_elements_by_xpath("//*[@id='tabP-1']/div/div[1]/div[1]/div[1]/p/a[2]")
for i in company:
    try:
        Company.append(i.text)
    except:
        Company.append("-")

In [10]:
#creating the skills
skills=driver.find_elements_by_xpath("//*[@id='tabP-1']/div/div[1]/div[1]/div[2]")
for i in skills:
    try:
        Skills.append(i.text)
    except:
        Skills.append("-")

In [11]:
#creating list for location
location=driver.find_elements_by_xpath("//*[@id='tabP-1']/div/div[1]/div[1]/div[1]/p/span[2]/small")
for i in location:
    try:
        Location.append(i.text)
    except:
        Location.append("-")

In [12]:
#creating the Data Frame
Data_scientist_recruiters=pd.DataFrame([])
Data_scientist_recruiters["Name"]=Name
Data_scientist_recruiters["Designation"]=Designation
Data_scientist_recruiters["Company"]=Company
Data_scientist_recruiters["Skills"]=Skills
Data_scientist_recruiters["Location"]=Location

In [13]:
#data frame
Data_scientist_recruiters

,Name,Designation,Company,Skills,Location
0,Tanushree,Lead Recruiter,RecRoots,"UI Developers, Software Engineers, Quality Ass...",Noida
1,Bitapi,HR and Operation Manager,Anvaya,"Hadoop, Big Data, Data Scientists, Java, Sprin...",Bengaluru / Bangalore
2,Sadashiv Kulkarni,Company HR,Digitially Insights Pvt Ltd,"Big Data Engineer, Data Scientist, Solutions, ...",Pune
3,Invelopment,Company HR,Invelopment,Scandinavian Startups,Ahmedabad
4,Anoop Somarajan,Assistant Manager Talent Acquisition,Access Healthcare,"Asp.net, Hl7, Mirth, Perl, Xamarin, Javascript...",Chennai
5,Ashish Verma,Senior Associate Human Resources,Evalueserve.com Private Limited,"SAS, VBA, Business Information Services(BIS), ...",Gurgaon
6,HS Sandesh,Talent Evangelist www staffiohr co,Staffio HR,"Digital Marketing, General Manager, Business D...",Bengaluru / Bangalore
7,A Valsa Florina,Recruitment Specialist,Redbus.in,"Business Analyst, Front end developer, legal, ...",Bengaluru / Bangalore
8,Prashant K,Sr HR,Confidential,"Data Analyst, Statistical Analysis, Data Scien...",Bengaluru / Bangalore
9,Rakhi,HR recruiter,Constalytics,"Data Scientist, Data Research Analyst, Big Dat...",Singapore - (singapore)
10,Trilok Nath,Senior IT Recruiter,Molveno Consulting Private Limited,".Net Developers With Angular Js, Html, Front E...",Hyderabad / Secunderabad
11,Rashmi Kathuria,Talent Acquisition Specialist (Specialized...,Mount Talent consulting,"Leading MNCs, Product based organizations",Noida
12,Monika Singh Thakur,Technical Recruiter,ValueLabs,"Big Data Analytics, Marketing Analytics, Full ...",Indore
13,Janhavi Soni,HR Generalist,Vihaa Technologies LLP,"C, C++, Unity3d, Core Php, Android Development...",Ahmedabad
14,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Mysoru / Mysore
15,Vivek Shrivastava,Assistant Manager Human Resources,InnovAccer Management Pvt Ltd,"Business Analyst, analytics, Decesion Scientis...",Noida
16,Best In Town Analytics,Analytics Associate,BITA,Data Analytics,Bengaluru / Bangalore
17,priyanka,General Manager,Reliance Industries,"Sap, Saas, Sql, Hadoop, Production Planning, B...",Mumbai
18,Roshan Menugu,Company Recruiter,Cyient Limited,Not Specified,Hyderabad / Secunderabad
19,Jamil Akhtar,Company Recruiter,Quikkloan,Not Specified,Delhi
20,navya neluri,Data Scientist,asens labs,Not Specified,Hyderabad / Secunderabad
21,Vanitha Senkurichi,Company HR,Quaero 3 India Ltd,"sql, Ui Development, ssis, Data Modeling, Data...",Bengaluru / Bangalore
22,Arya,Human Resources Manager,Arya.ai,"Artificial Intelligence, Deep Learning, Machin...",Mumbai
23,Ms Uma,Company HR,RenovITe Payment Solutions Pvt ltd,"java, J2ee, activemq, rest, cassandra, redis, ...",Noida
24,Kranthi Kumar M,Lead HR Talent Acquisition,PrimEra Medical Technologies Private...,"Medical Coders, mbbs, bi, appeals, master data...",Hyderabad / Secunderabad